export const links = [
  {
    label: 'Home',
    href: '/',
  },
  {
    label: 'Empreendimentos',
    href: '/empreendimentos',
  },
  {
    label: 'Blog',
    href: '/blog',
  },
  {
    label: 'Contato',
    href: '/contato',
  },
];

export const zonas = ['Centro', 'Zona Sul', 'Zona Leste', 'Zona Oeste'];

export const regions = [
  'Aclimação',
  'Aricanduva',
  'Artur Alvim',
  'Bela Vista',
  'Berrini',
  'Cambuci',
  'Campo Belo',
  'Campo Limpo',
  'Cangaíba',
  'Casa Verde',
  'Centro',
  'Congonhas',
  'Cupecê',
  'Dom Bosco',
  'Estação Lapa',
  'Estação Sacomã',
  'Freguesia do Ó',
  'Giovanni Gronchi',
  'Guilhermina Esperança',
  'Interlagos',
  'Ipiranga',
  'Itaquera',
  'Jaçanã',
  'Jaraguá',
  'Jardim Aeroporto',
  'Jardim Boa Esperança',
  'Jardim Jabaquara',
  'Jardim Miriam',
  'Jardim Paulista',
  'João Paulo I',
  'Lapa',
  'Liberdade',
  'Mooca',
  'Morumbi',
  'Panamby',
  'Parque do Carmo',
  'Penha',
  'Pinheiros',
  'Pirituba',
  'Real Parque',
  'República',
  'Sacoma',
  'Santa Cruz',
  'Santo Amaro',
  'São Miguel',
  'Saúde',
  'Vila Carmosina',
  'Vila das Belezas',
  'Vila Dom Pedro I',
  'Vila dos Remédios',
  'Vila Ema',
  'Vila Esperança',
  'Vila Gomes',
  'Vila Matilde',
  'Vila Pereira Barreto',
  'Vila Prudente',
  'Vila Ré',
  'Vila Romana',
  'Vila Sônia',
  'Vila Sylvia',
];
